import {  Roboto_Flex } from 'next/font/google'
import { getCssText } from '@/styles'
import { globalStyles } from '@/styles/global'
import Image from 'next/image'

import logo from '@/assets/logo.svg'
import {Container, Header} from '@/styles/pages/app'

// const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto_Flex({subsets: ['latin']})
// const acme = Acme({subsets: ['latin'], weight: '400', variable: '--font-t'} ,)

globalStyles()

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  
  return (
    <html lang="en" className={roboto.className}>
      <head>
        <style id='stiches' dangerouslySetInnerHTML={{__html: getCssText()}}/>
      </head>
      <body>
        <Container>
          <Header>
            <Image src={logo} alt="" />
          </Header>
          {children}
        </Container>
      </body>
    </html>
  )
}
